name: ðŸš€ Deploy website on Live Server
on:
  push:
    branches:
      - saas
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy on Saas Branch
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
#          run:
#            cd staging.esholiday.com
#            git pull
#            cd backendApi/
#            php artisan route:clear
#            php artisan cache:clear
#            php artisan config:clear
#            php artisan route:cache
#            php artisan optimize
#            php artisan migrate
#            composer dump-autoload
          server: ${{ secrets.server_host }}
          port: ${{ secrets.port }} 
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /staging.esholiday.com/
#          script: "cd /var/www/html && ./.scripts/deploy.sh"


